name: E2E Functionality Check
on:
  pull_request:
    branches: [ master ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.23.7

jobs:
  kind-e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.33.2", "v1.30.13", "v1.28.15", "v1.24.17", "v1.22.17"]
    env:
      workspace: ${{ github.workspace }}
      KIND_CLUSTER: fluid-cluster
    defaults:
      run:
        working-directory: ${{ env.workspace }}

    steps:
      
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: ${{ env.workspace }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: v0.29.0  # default version in v1.12.0 is v0.24.0, bump to v0.29.0 to solve https://github.com/kubernetes-sigs/kind/issues/3853
          node_image: kindest/node:${{ matrix.kubernetes-version }}
          cluster_name: ${{ env.KIND_CLUSTER }}
          kubectl_version: ${{ matrix.kubernetes-version }}

      - name: Deploy fluid to Kind cluster
        run: |
          ./.github/scripts/deploy-fluid-to-kind.sh

      - name: Fluid basic e2e tests
        timeout-minutes: 30
        run: |
          ./.github/scripts/gha-e2e.sh

      - name: Dump environment
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: gha-e2e-logs-${{ github.job }}-${{ matrix.kubernetes-version }}
          path: "src/github.com/fluid-cloudnative/charts/e2e-tmp/testcase-*.tgz"
          retention-days: 14